use rehabilitar_testing;

SET foreign_key_checks = 0;
drop table campos;
drop table campos_informacion;

create table campos(
     id int auto_increment,
     id_area int,
     name varchar(500),
     label varchar(1000),
     type varchar(500),
     options varchar(1000),
     default_value varchar(500),
     form_orden int,
     categoria_form varchar(100) default null,
     
     primary key (id)
);

create table campos_informacion(
	id int auto_increment,
    id_campo int,
    id_turno int,
    value varchar(1000),
    id_adjunto int,
    
    primary key (id),
    foreign key (id_turno) references turnos(id),
    foreign key (id_campo) references campos(id)
);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (NULL, NULL, 'DDJJ', NULL, NULL, NULL, NULL,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (NULL, 'title_consentimiento1', 'CONSENTIMIENTO', 'text', NULL, NULL, NULL,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (NULL, 'title_consentimiento2', 'CONSENTIMIENTO INFORMADO PARA EXAMENES DE LABORATORIO', 'text', NULL, NULL, NULL,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (NULL, 'title_consentimiento3', 'POR LA PRESENTE AUTORIZO A LA EMPRESA REHABILITAR SAN JUAN S.R.L. SE ME EFECTUEN LOS SIGUIENTES ANALISIS DECLARANDO QUE SE ME EXPLICO CADA UNO DE ELLOS Y DOY MI CONSENTIMIENTO LIBREMENTE.

ACEPTO SE ME REALICEN PRUEBAS EN ORINA PARA DOSAJE DE SUSTANCIAS DE ADICCION: MARIHUANA Y COCAINA.', 'text', NULL, NULL, NULL,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (NULL, NULL, 'Firma Paciente', NULL, NULL, NULL, NULL,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title_clinico_1', 'EXAMEN CLINICO', 'text', NULL, NULL, 1.0,'general');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title_clinico_2', 'EXAMEN CLINICO', 'text', NULL, NULL, 2.0,'general');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_Enfermedades', 'Enfermedades y Operaciones previas: ', 'input', NULL, NULL, 3.0,'general');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_Peso', 'Peso: ', 'input', NULL, NULL, 4.0,'general');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_Estatura', 'Estatura: ', 'input', NULL, NULL, 5.0,'general');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_Lado', 'Lado habil: ', 'input', NULL, NULL, 6.0,'general');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_TA1', 'TA 1deg: ', 'input', NULL, NULL, 7.0,'general');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_FC', 'FC:', 'input', NULL, NULL, 8.0,'general');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_IMC', 'IMC:', 'input', NULL, NULL, 9.0,'general');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_ApCirculatorio', 'Ap. Circulatorio: ', 'input', NULL, NULL, 10.0,'general');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_ApRespiratorio', 'Ap. Respiratorio: ', 'input', NULL, NULL, 11.0,'general');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_ApDigestivo', 'Ap. Digestivo: ', 'input', NULL, NULL, 12.0,'general');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_ApGenitoUrinario', 'Ap. Genito Urinario: ', 'input', NULL, NULL, 13.0,'general');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_SNervCentral', 'S. Nerv. Central: ', 'input', NULL, NULL, 14.0,'general');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_SMuscular', 'S. Muscular, hernias o eventraciones: ', 'input', NULL, NULL, 15.0,'general');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_Columna', 'Columna vertebral y S. Osteoarticular: ', 'input', NULL, NULL, 16.0,'general');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_MSuperiorD', 'Miembro Superior Derecho: ', 'input', NULL, NULL, 17.0,'general');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_MSuperiorI', 'Miembro Superior Izquierdo: ', 'input', NULL, NULL, 18.0,'general');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_MInferiorD', 'Miembro Inferior Derecho: ', 'input', NULL, NULL, 19.0,'general');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_MInferiorI', 'Miembro Inferior Izquierdo: ', 'input', NULL, NULL, 20.0,'general');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_Piel', 'Piel: ', 'input', NULL, NULL, 21.0,'general');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_Vision', 'Vision: ', 'input', NULL, NULL, 22.0,'general');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_OD', 'OD:', 'input', NULL, NULL, 23.0,'general');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_IOI', 'IOI', 'input', NULL, NULL, 24.0,'general');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_Audicion', 'Audicion:', 'input', NULL, NULL, 25.0,'general');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_Dentadura', 'Dentadura: ', 'input', NULL, NULL, 26.0,'general');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_Embarazos', 'Embarazos:', 'input', NULL, NULL, 27.0,'general');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_Partos', 'Partos:', 'input', NULL, NULL, 28.0,'general');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_Cesareas', 'Cesareas:', 'input', NULL, NULL, 29.0,'general');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_Abortos', 'Abortos:', 'input', NULL, NULL, 30.0,'general');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_Conclusion', 'Conclusion:', 'checkbox', 'Apto, No Apto, Apto con Prescripcion', NULL, 31.0,'general');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_Observaciones', 'Observaciones:', 'input', NULL, NULL, 32.0,'general');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title_clinico_3', 'FICHA DE DETECCION DE S.A.S.', 'text', NULL, NULL, 1.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title_clinico_FILIACION', '1- FILIACION', 'text', NULL, NULL, 2.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, NULL, 'Apellidos y Nombres: ', NULL, NULL, NULL, 3.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, NULL, 'Fecha:', NULL, NULL, NULL, 4.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, NULL, 'D.N.I.: ', NULL, NULL, NULL, 5.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_FNacimiento', 'F. Nacimiento:', 'input', NULL, NULL, 6.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_Sexo', 'Sexo:', 'input', NULL, NULL, 7.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_AreaTrabajo', 'Area Trabajo: ', 'input', NULL, NULL, 8.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_TipoLicencia', 'Tipo Licencia:', 'input', NULL, NULL, 9.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_Empresa', 'Empresa: ', 'input', NULL, NULL, 10.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_PuestoTrabajo', 'Puesto Trabajo:', 'input', NULL, NULL, 11.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_Trabajadenoche', 'Trabaja de noche:', 'checkbox', NULL, NULL, 12.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_Diasdetrabajo', 'Dias de trabajo:', 'input', NULL, NULL, 13.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_DiasdeDescanso', 'Dias de Descanso:', 'input', NULL, NULL, 14.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_Anos', 'Anos que trabaja en dicho horario de trabajo:', 'input', NULL, NULL, 15.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title_clinico_2- ANTPERSONALES', '2- ANTECEDENTES PERSONALES', 'text', NULL, NULL, 16.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_Apnea', 'Apnea del sueno:', 'checkbox', NULL, NULL, 17.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'date_clinico_UltimoControl', 'Ultimo Control:', 'date', NULL, NULL, 18.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_HTA', 'HTA: Medicacion: (Riesgo>2)', 'checkbox', NULL, NULL, 19.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_PSG', 'Polisomnografia (PSG) realizada alguna vez: ', 'checkbox', NULL, NULL, 20.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'date_clinico_FechaPSG', 'Fecha de ultima PSG:', 'date', NULL, NULL, 21.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_Antchoque', 'Antecedente de choque de vehiculo(Si es NO, pase a seccion 4):', 'checkbox', 'En mina, Fuera de mina', NULL, 22.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title_clinico_Detalle', 'Detalle lo siguiente de los antecedentes del (los) choques (incidentes o accidentes):', 'text', NULL, NULL, 23.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_Criterio1', 'Criterio 1: Se "cabeceo" y por ello le ocurrio un accidente (incidente) con un vehiculo (alguna vez):', 'checkbox', NULL, NULL, 24.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title_clinico_Criterio2', 'Criterio 2: (2 o mas es positivo)', 'text', NULL, NULL, 25.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_Criterio2-1', 'Accidente ocurrido entre las 0 horas y las 7 horas de la manana o entre las 13 y 15 horas (tarde)', 'checkbox', NULL, NULL, 26.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_Criterio2-2', 'No hubo evidencia de maniobra evasiva del chofer para evitar la colision', 'checkbox', NULL, NULL, 27.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_Criterio2-3', 'Colision frontal del vehiculo', 'checkbox', NULL, NULL, 28.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_Criterio2-4', 'Vehiculo que invadio el otro carril o se desvio sin causa aparente', 'checkbox', NULL, NULL, 29.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_Criterio2-5', 'La unidad cayo a un barranco, rio o choco un poste, puente, edificio u otra estructura estatica sin causa aparente', 'checkbox', NULL, NULL, 30.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_Criterio2-6', 'Chofer viajaba solo en el vehiculo', 'checkbox', NULL, NULL, 31.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_Criterio2-7', 'Chofer no tenia copiloto y cumplia o acababa de terminar una jornada larga de trabajo (mas de 8 horas)', 'checkbox', NULL, NULL, 32.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title_clinico_Clasif', 'Clasificacion del (los) "choques" o accidentes vehiculares del postulante (marque solo una categoria)', 'text', NULL, NULL, 33.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_Clasif-1', 'Accidente confirmado por Somnolencia (Criterio 1 positivo)', 'checkbox', NULL, NULL, 34.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_Clasif-2', 'Accidente con alta sospecha de Somnolencia (Criterio 2 positivo)', 'checkbox', NULL, NULL, 35.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_Clasif-3', 'Accidente con escasa evidencia/sospecha por somnolencia (solo 1 item de Criterio 2)', 'checkbox', NULL, NULL, 36.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_Clasif-4', 'No se dispone de datos suficientes para clasificar el (los) incidentes', 'checkbox', NULL, NULL, 37.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_Clasif-5', 'Accidente no debido a somnolencia (informacion suficiente que descarta la somnolencia)', 'checkbox', NULL, NULL, 38.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title_clinico_ANTFAMILIAR', '3- ANTECEDENTE FAMILIAR DE APNEA DEL SUENO', 'text', NULL, NULL, 39.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_Antfamiliar', 'Antecedente familiar de apnea del sueno', 'checkbox', NULL, NULL, 40.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title_clinico_ENTREVISTA', '4-ENTREVISTA AL PACIENTE', 'text', NULL, NULL, 41.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_ENTREVISTA-1', 'En los ultimos 5 anos, su pareja o esposa le ha comentado que ronca al dormir', 'checkbox', NULL, NULL, 42.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_ENTREVISTA-2', 'En los ultimos 5 anos, su pareja o esposa le ha comentado que hace ruidos al respirar mientras duerme', 'checkbox', NULL, NULL, 43.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_ENTREVISTA-3', 'En los ultimos 5 anos, su pareja o esposa le ha comentado que deja de respirar cuando duerme (pausa respiratoria)', 'checkbox', NULL, NULL, 44.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_ENTREVISTA-4', 'Comparado con sus companeros, usted siente que tiene mas sueno o cansancio que ellos mientras trabaja', 'checkbox', NULL, NULL, 45.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_ENTREVISTA-5', 'Ha tenido algun accidente o incidente vehicular porque se cabeceo', 'checkbox', NULL, NULL, 46.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_ENTREVISTA-6', 'Ha tenido algun accidente o incidente vehicular considerado "por falla humana"', 'checkbox', NULL, NULL, 47.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_ENTREVISTA-7', 'Esta recibiendo tratamiento para Apnea del sueno con CPAP', 'checkbox', NULL, NULL, 48.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_ENTREVISTA-8', 'Se ha realizado una PSG durante el sueno para descartar un trastorno del sueno', 'checkbox', NULL, NULL, 49.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_PUNTUACION', 'PUNTUACION DE LA ESCALA DE EPWORTH (ESS)', 'input', NULL, NULL, 50.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title_clinico_EXFISICO', '5-EXAMEN FISICO', 'text', NULL, NULL, 51.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title_clinico_Evaluacion', 'Evaluacion de via superior', 'text', NULL, NULL, 52.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_GradoI', 'Grado I', 'checkbox', NULL, NULL, 53.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_GradoII', 'Grado II', 'checkbox', NULL, NULL, 54.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_GradoIII', 'Grado III', 'checkbox', NULL, NULL, 55.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_GradoIV', 'Grado IV', 'checkbox', NULL, NULL, 56.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title_clinico_CONCLUSION', '6-CONCLUSION DE LA EVALUACION', 'text', NULL, NULL, 57.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title_clinico_RequierePSG', 'Requiere PSG antes de certificar aptitud para conducir (un criterio positivo)', 'text', NULL, NULL, 58.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CriterioA', 'Criterio A: Excesiva somnolencia determinada por ESS mayor de 15 o cabeceo presenciado durante la
evaluacion (espera), antecedentes de accidente por somnolencia o con alta sospecha por
somnolencia.', 'checkbox', NULL, NULL, 59.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CriterioB', 'Criterio B: Antecedentes de SAS sin control reciente o sin cumplimiento de tratamiento (con CPAP o cirugia)', 'checkbox', NULL, NULL, 60.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title_clinico_Apto3', 'Apto por 3 meses a renovar luego de PSG (un criterio positivo)', 'text', NULL, NULL, 61.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CriterioC', 'Criterio C: Historia de higiene de sueno sugiere SAS (presencia de ronquidos, somnolencia excesiva
durante la actividad, pausas respiratorias)', 'checkbox', NULL, NULL, 62.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CriterioD', 'Criterio D: Cumple con 2 o mas de los siguientes:
IMC mayor o igual a 35
Hipertension Arterial (nueva, no controlada con una sola medicacion)
Circunferencia del cuello anormal
Puntuacion de Eptworth mayor de 10 y menor de 16
Antecedente de trastorno del sueno (diagnosticado) sin seguimiento
Indice de Apnea-hipopnea (AHI) mayor de 5 y menor de 30', 'checkbox', NULL, NULL, 63.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CriterioE', 'Criterio E: Evaluacion de via aerea superior patologico*', 'checkbox', NULL, NULL, 64.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_Aptobajoriesgo', 'Apto con bajo riesgo de Apnea del sueno (ningun criterio positivo)', 'checkbox', NULL, NULL, 65.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_NyAMedico', 'Nombre y Apellidos del Medico:', 'input', NULL, NULL, 66.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_Observaciones', 'Observaciones/recomendaciones:', 'input', NULL, NULL, 67.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title_clinico_ESCALA', 'ESCALA DE SOMNOLENCIA DE EPWORT', 'text', NULL, NULL, 68.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title_clinico_probable', '?Que tan probable es que usted se sienta somnoliento o se duerma en las siguientes situaciones?', 'text', NULL, NULL, 69.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_Sentado1', 'Sentado leyendo', 'checkbox', 'Nunca,Baja,Moderada,Alta', NULL, 70.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_MirandoTV', 'Mirando television', 'checkbox', 'Nunca,Baja,Moderada,Alta', NULL, 71.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_Sentado2', 'Sentado sin hacer nada en un lugar publico', 'checkbox', 'Nunca,Baja,Moderada,Alta', NULL, 72.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_Acostado', 'Acostado, descansado en la tarde', 'checkbox', 'Nunca,Baja,Moderada,Alta', NULL, 73.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_pasajeroauto', 'Como pasajero en un auto durante una hora de viaje', 'checkbox', 'Nunca,Baja,Moderada,Alta', NULL, 74.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_Sentado3', 'Sentado y conversando con alguien', 'checkbox', 'Nunca,Baja,Moderada,Alta', NULL, 75.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_Sentado4', 'Sentado, tranquilo, despues de almorzar sin tomar alcohol', 'checkbox', 'Nunca,Baja,Moderada,Alta', NULL, 76.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_autodetenido', 'En un auto mientras se detiene unos momentos por el trafico', 'checkbox', 'Nunca,Baja,Moderada,Alta', NULL, 77.0,'sas');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title_clinico_HISTORIA', 'HISTORIA OCUPACIONAL', 'text', NULL, NULL, 1.0,'ocupacional');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'date_clinico_FInicio', 'F.Inicio', 'date', NULL, NULL, 2.0,'ocupacional');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_Empresa', 'Empresa: ', 'input', NULL, NULL, 3.0,'ocupacional');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_Altitud', 'Altitud', 'input', NULL, NULL, 4.0,'ocupacional');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_ActEmpresa', 'Act. de la Empresa', 'input', NULL, NULL, 5.0,'ocupacional');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_Area', 'Area de Trabajo', 'input', NULL, NULL, 6.0,'ocupacional');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_Ocupacion', 'Ocupacion', 'input', NULL, NULL, 7.0,'ocupacional');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_Subsuelo', 'Subsuelo', 'input', NULL, NULL, 8.0,'ocupacional');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_Superficie', 'Superficie', 'input', NULL, NULL, 9.0,'ocupacional');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_PeligrosAgentesOcup', 'Peligros Agentes Ocup.', 'input', NULL, NULL, 10.0,'ocupacional');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'input_clinico_UsoEPP', 'Uso EPP- Tipo EPP', 'input', NULL, NULL, 11.0,'ocupacional');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title_clinico_CUESTMOLMUSCULOESQUELETICAS', 'CUESTIONARIO DE MOLESTIAS MUSCULOESQUELETICAS', 'text', NULL, NULL, 1.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title2_clinico_ZONACORPORTAL', 'ZONA CORPORTAL', 'text', NULL, NULL, 2.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title3_clinico_CMM1', '1 Cuello', 'text', NULL, NULL, 3.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title4_clinico_CMM1A', 'A ?Durante los ultimos meses, ha tenido en el trabajo dolor, molestias o incomodidan en los musculos, huesos o articulaciones? (No considerar molestias debidas a accidentes producidos fuera del trabajo).', 'text', NULL, NULL, 4.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM1ANo', 'No (Pasar a la siguiente zona corporal)', 'checkbox', NULL, NULL, 5.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM1ASi', 'Si (Pasar a la pregunta B)', 'checkbox', NULL, NULL, 6.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title4_clinico_CMM1B', 'B ?Persisten estas molestias fuera del trabajo?', 'text', NULL, NULL, 7.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM1BNo', 'No', 'checkbox', NULL, NULL, 8.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM1BSi', 'Si', 'checkbox', NULL, NULL, 9.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title4_clinico_CMM1C', 'C ?Estas molestias, le has impedido realizar normalmente su actividad laboral?', 'text', NULL, NULL, 10.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM1CNo', 'No', 'checkbox', NULL, NULL, 11.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM1CSi', 'Si', 'checkbox', NULL, NULL, 12.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title4_clinico_CMM1D', 'D ?Ha acudido a algun fisioterapeuta o medico a causa de estas molestias?', 'text', NULL, NULL, 13.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM1DNo', 'No', 'checkbox', NULL, NULL, 14.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM1DSi', 'Si', 'checkbox', NULL, NULL, 15.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title4_clinico_CMM1E', 'E ?Ha perdido dias de trabajo a causa de estas molestias?', 'text', NULL, NULL, 16.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM1ENo', 'No', 'checkbox', NULL, NULL, 17.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM1ESi', 'Si', 'checkbox', NULL, NULL, 18.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title3_clinico_CMM2', '2 Zona Dorsal Espalda', 'text', NULL, NULL, 19.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title4_clinico_CMM2A', 'A ?Durante los ultimos meses, ha tenido en el trabajo dolor, molestias o incomodidan en los musculos, huesos o articulaciones? (No considerar molestias debidas a accidentes producidos fuera del trabajo).', 'text', NULL, NULL, 20.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM2ANo', 'No (Pasar a la siguiente zona corporal)', 'checkbox', NULL, NULL, 21.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM2ASi', 'Si (Pasar a la pregunta B)', 'checkbox', NULL, NULL, 22.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title4_clinico_CMM2B', 'B ?Persisten estas molestias fuera del trabajo?', 'text', NULL, NULL, 23.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM2BNo', 'No', 'checkbox', NULL, NULL, 24.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM2BSi', 'Si', 'checkbox', NULL, NULL, 25.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title4_clinico_CMM2C', 'C ?Estas molestias, le has impedido realizar normalmente su actividad laboral?', 'text', NULL, NULL, 26.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM2CNo', 'No', 'checkbox', NULL, NULL, 27.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM2CSi', 'Si', 'checkbox', NULL, NULL, 28.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title4_clinico_CMM2D', 'D ?Ha acudido a algun fisioterapeuta o medico a causa de estas molestias?', 'text', NULL, NULL, 29.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM2DNo', 'No', 'checkbox', NULL, NULL, 30.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM2DSi', 'Si', 'checkbox', NULL, NULL, 31.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title4_clinico_CMM2E', 'E ?Ha perdido dias de trabajo a causa de estas molestias?', 'text', NULL, NULL, 32.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM2ENo', 'No', 'checkbox', NULL, NULL, 33.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM2ESi', 'Si', 'checkbox', NULL, NULL, 34.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title3_clinico_CMM3', '3 Zona Lumbar Espalda', 'text', NULL, NULL, 35.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title4_clinico_CMM3A', 'A ?Durante los ultimos meses, ha tenido en el trabajo dolor, molestias o incomodidan en los musculos, huesos o articulaciones? (No considerar molestias debidas a accidentes producidos fuera del trabajo).', 'text', NULL, NULL, 36.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM3ANo', 'No (Pasar a la siguiente zona corporal)', 'checkbox', NULL, NULL, 37.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM3ASi', 'Si (Pasar a la pregunta B)', 'checkbox', NULL, NULL, 38.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title4_clinico_CMM3B', 'B ?Persisten estas molestias fuera del trabajo?', 'text', NULL, NULL, 39.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM3BNo', 'No', 'checkbox', NULL, NULL, 40.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM3BSi', 'Si', 'checkbox', NULL, NULL, 41.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title4_clinico_CMM3C', 'C ?Estas molestias, le has impedido realizar normalmente su actividad laboral?', 'text', NULL, NULL, 42.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM3CNo', 'No', 'checkbox', NULL, NULL, 43.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM3CSi', 'Si', 'checkbox', NULL, NULL, 44.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title4_clinico_CMM3D', 'D ?Ha acudido a algun fisioterapeuta o medico a causa de estas molestias?', 'text', NULL, NULL, 45.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM3DNo', 'No', 'checkbox', NULL, NULL, 46.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM3DSi', 'Si', 'checkbox', NULL, NULL, 47.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title4_clinico_CMM3E', 'E ?Ha perdido dias de trabajo a causa de estas molestias?', 'text', NULL, NULL, 48.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM3ENo', 'No', 'checkbox', NULL, NULL, 49.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM3ESi', 'Si', 'checkbox', NULL, NULL, 50.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title3_clinico_CMM4', '4 Hombros-Brazos', 'text', NULL, NULL, 51.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title4_clinico_CMM4A', 'A ?Durante los ultimos meses, ha tenido en el trabajo dolor, molestias o incomodidan en los musculos, huesos o articulaciones? (No considerar molestias debidas a accidentes producidos fuera del trabajo).', 'text', NULL, NULL, 52.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM4ANo', 'No (Pasar a la siguiente zona corporal)', 'checkbox', NULL, NULL, 53.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM4ASi', 'Si (Pasar a la pregunta B)', 'checkbox', NULL, NULL, 54.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title4_clinico_CMM4B', 'B ?Persisten estas molestias fuera del trabajo?', 'text', NULL, NULL, 55.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM4BNo', 'No', 'checkbox', NULL, NULL, 56.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM4BSi', 'Si', 'checkbox', NULL, NULL, 57.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title4_clinico_CMM4C', 'C ?Estas molestias, le has impedido realizar normalmente su actividad laboral?', 'text', NULL, NULL, 58.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM4CNo', 'No', 'checkbox', NULL, NULL, 59.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM4CSi', 'Si', 'checkbox', NULL, NULL, 60.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title4_clinico_CMM4D', 'D ?Ha acudido a algun fisioterapeuta o medico a causa de estas molestias?', 'text', NULL, NULL, 61.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM4DNo', 'No', 'checkbox', NULL, NULL, 62.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM4DSi', 'Si', 'checkbox', NULL, NULL, 63.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title4_clinico_CMM4E', 'E ?Ha perdido dias de trabajo a causa de estas molestias?', 'text', NULL, NULL, 64.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM4ENo', 'No', 'checkbox', NULL, NULL, 65.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM4ESi', 'Si', 'checkbox', NULL, NULL, 66.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title3_clinico_CMM5', '5 Codos-Antebrazos', 'text', NULL, NULL, 67.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title4_clinico_CMM5A', 'A ?Durante los ultimos meses, ha tenido en el trabajo dolor, molestias o incomodidan en los musculos, huesos o articulaciones? (No considerar molestias debidas a accidentes producidos fuera del trabajo).', 'text', NULL, NULL, 68.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM5ANo', 'No (Pasar a la siguiente zona corporal)', 'checkbox', NULL, NULL, 69.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM5ASi', 'Si (Pasar a la pregunta B)', 'checkbox', NULL, NULL, 70.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title4_clinico_CMM5B', 'B ?Persisten estas molestias fuera del trabajo?', 'text', NULL, NULL, 71.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM5BNo', 'No', 'checkbox', NULL, NULL, 72.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM5BSi', 'Si', 'checkbox', NULL, NULL, 73.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title4_clinico_CMM5C', 'C ?Estas molestias, le has impedido realizar normalmente su actividad laboral?', 'text', NULL, NULL, 74.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM5CNo', 'No', 'checkbox', NULL, NULL, 75.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM5CSi', 'Si', 'checkbox', NULL, NULL, 76.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title4_clinico_CMM5D', 'D ?Ha acudido a algun fisioterapeuta o medico a causa de estas molestias?', 'text', NULL, NULL, 77.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM5DNo', 'No', 'checkbox', NULL, NULL, 78.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM5DSi', 'Si', 'checkbox', NULL, NULL, 79.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title4_clinico_CMM5E', 'E ?Ha perdido dias de trabajo a causa de estas molestias?', 'text', NULL, NULL, 80.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM5ENo', 'No', 'checkbox', NULL, NULL, 81.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM5ESi', 'Si', 'checkbox', NULL, NULL, 82.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title3_clinico_CMM6', '6 Munecas-Manos', 'text', NULL, NULL, 83.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title4_clinico_CMM6A', 'A ?Durante los ultimos meses, ha tenido en el trabajo dolor, molestias o incomodidan en los musculos, huesos o articulaciones? (No considerar molestias debidas a accidentes producidos fuera del trabajo).', 'text', NULL, NULL, 84.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM6ANo', 'No (Pasar a la siguiente zona corporal)', 'checkbox', NULL, NULL, 85.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM6ASi', 'Si (Pasar a la pregunta B)', 'checkbox', NULL, NULL, 86.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title4_clinico_CMM6B', 'B ?Persisten estas molestias fuera del trabajo?', 'text', NULL, NULL, 87.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM6BNo', 'No', 'checkbox', NULL, NULL, 88.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM6BSi', 'Si', 'checkbox', NULL, NULL, 89.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title4_clinico_CMM6C', 'C ?Estas molestias, le has impedido realizar normalmente su actividad laboral?', 'text', NULL, NULL, 90.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM6CNo', 'No', 'checkbox', NULL, NULL, 91.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM6CSi', 'Si', 'checkbox', NULL, NULL, 92.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title4_clinico_CMM6D', 'D ?Ha acudido a algun fisioterapeuta o medico a causa de estas molestias?', 'text', NULL, NULL, 93.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM6DNo', 'No', 'checkbox', NULL, NULL, 94.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM6DSi', 'Si', 'checkbox', NULL, NULL, 95.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title4_clinico_CMM6E', 'E ?Ha perdido dias de trabajo a causa de estas molestias?', 'text', NULL, NULL, 96.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM6ENo', 'No', 'checkbox', NULL, NULL, 97.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM6ESi', 'Si', 'checkbox', NULL, NULL, 98.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title3_clinico_CMM7', '7 Caderas-Nalgas-Muslos', 'text', NULL, NULL, 99.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title4_clinico_CMM7A', 'A ?Durante los ultimos meses, ha tenido en el trabajo dolor, molestias o incomodidan en los musculos, huesos o articulaciones? (No considerar molestias debidas a accidentes producidos fuera del trabajo).', 'text', NULL, NULL, 100.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM7ANo', 'No (Pasar a la siguiente zona corporal)', 'checkbox', NULL, NULL, 101.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM7ASi', 'Si (Pasar a la pregunta B)', 'checkbox', NULL, NULL, 102.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title4_clinico_CMM7B', 'B ?Persisten estas molestias fuera del trabajo?', 'text', NULL, NULL, 103.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM7BNo', 'No', 'checkbox', NULL, NULL, 104.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM7BSi', 'Si', 'checkbox', NULL, NULL, 105.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title4_clinico_CMM7C', 'C ?Estas molestias, le has impedido realizar normalmente su actividad laboral?', 'text', NULL, NULL, 106.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM7CNo', 'No', 'checkbox', NULL, NULL, 107.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM7CSi', 'Si', 'checkbox', NULL, NULL, 108.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title4_clinico_CMM7D', 'D ?Ha acudido a algun fisioterapeuta o medico a causa de estas molestias?', 'text', NULL, NULL, 109.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM7DNo', 'No', 'checkbox', NULL, NULL, 110.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM7DSi', 'Si', 'checkbox', NULL, NULL, 111.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title4_clinico_CMM7E', 'E ?Ha perdido dias de trabajo a causa de estas molestias?', 'text', NULL, NULL, 112.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM7ENo', 'No', 'checkbox', NULL, NULL, 113.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM7ESi', 'Si', 'checkbox', NULL, NULL, 114.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title3_clinico_CMM8', '8 Rodillas-Piernas', 'text', NULL, NULL, 115.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title4_clinico_CMM8A', 'A ?Durante los ultimos meses, ha tenido en el trabajo dolor, molestias o incomodidan en los musculos, huesos o articulaciones? (No considerar molestias debidas a accidentes producidos fuera del trabajo).', 'text', NULL, NULL, 116.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM8ANo', 'No (Pasar a la siguiente zona corporal)', 'checkbox', NULL, NULL, 117.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM8ASi', 'Si (Pasar a la pregunta B)', 'checkbox', NULL, NULL, 118.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title4_clinico_CMM8B', 'B ?Persisten estas molestias fuera del trabajo?', 'text', NULL, NULL, 119.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM8BNo', 'No', 'checkbox', NULL, NULL, 120.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM8BSi', 'Si', 'checkbox', NULL, NULL, 121.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title4_clinico_CMM8C', 'C ?Estas molestias, le has impedido realizar normalmente su actividad laboral?', 'text', NULL, NULL, 122.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM8CNo', 'No', 'checkbox', NULL, NULL, 123.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM8CSi', 'Si', 'checkbox', NULL, NULL, 124.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title4_clinico_CMM8D', 'D ?Ha acudido a algun fisioterapeuta o medico a causa de estas molestias?', 'text', NULL, NULL, 125.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM8DNo', 'No', 'checkbox', NULL, NULL, 126.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM8DSi', 'Si', 'checkbox', NULL, NULL, 127.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title4_clinico_CMM8E', 'E ?Ha perdido dias de trabajo a causa de estas molestias?', 'text', NULL, NULL, 128.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM8ENo', 'No', 'checkbox', NULL, NULL, 129.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM8ESi', 'Si', 'checkbox', NULL, NULL, 130.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'tilte3_clinico_CMM9', '9 Tobillos-Pies', 'text', NULL, NULL, 131.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title4_clinico_CMM9A', 'A ?Durante los ultimos meses, ha tenido en el trabajo dolor, molestias o incomodidan en los musculos, huesos o articulaciones? (No considerar molestias debidas a accidentes producidos fuera del trabajo).', 'text', NULL, NULL, 132.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM9ANo', 'No (Pasar a la siguiente zona corporal)', 'checkbox', NULL, NULL, 133.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM9ASi', 'Si (Pasar a la pregunta B)', 'checkbox', NULL, NULL, 134.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title4_clinico_CMM9B', 'B ?Persisten estas molestias fuera del trabajo?', 'text', NULL, NULL, 135.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM9BNo', 'No', 'checkbox', NULL, NULL, 136.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM9BSi', 'Si', 'checkbox', NULL, NULL, 137.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title4_clinico_CMM9C', 'C ?Estas molestias, le has impedido realizar normalmente su actividad laboral?', 'text', NULL, NULL, 138.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM9CNo', 'No', 'checkbox', NULL, NULL, 139.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM9CSi', 'Si', 'checkbox', NULL, NULL, 140.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title4_clinico_CMM9D', 'D ?Ha acudido a algun fisioterapeuta o medico a causa de estas molestias?', 'text', NULL, NULL, 141.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM9DNo', 'No', 'checkbox', NULL, NULL, 142.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM9DSi', 'Si', 'checkbox', NULL, NULL, 143.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'title4_clinico_CMM9E', 'E ?Ha perdido dias de trabajo a causa de estas molestias?', 'text', NULL, NULL, 144.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM9ENo', 'No', 'checkbox', NULL, NULL, 145.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (2.0, 'checkbox_clinico_CMM9ESi', 'Si', 'checkbox', NULL, NULL, 146.0,'nordico');
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (7.0, 'title_oftalmologia_1', 'OFTALMOLOGIA', 'text', NULL, NULL, 1.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (7.0, 'title_oftalmologia_Agudeza', 'Agudeza Visual', 'text', NULL, NULL, 2.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (7.0, 'input_oftalmologia_OD', 'O.D.: ', 'input', NULL, NULL, 3.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (7.0, 'input_oftalmologia_OI', 'O.I.: ', 'input', NULL, NULL, 4.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (7.0, 'title_oftalmologia_Presion', 'Presion Ocular (mmHg)', 'text', NULL, NULL, 5.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (7.0, 'input_oftalmologia_OD2', 'O.D.:', 'input', NULL, NULL, 6.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (7.0, 'input_oftalmologia_OI2', 'O.I.:', 'input', NULL, NULL, 7.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (7.0, 'title_oftalmologia_Test', 'Test de Colores', 'text', NULL, NULL, 8.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (7.0, 'input_oftalmologia_test', NULL, 'input', NULL, NULL, 9.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (7.0, 'title_oftalmologia_FondodeOjos', 'Fondo de Ojos', 'text', NULL, NULL, 10.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (7.0, 'input_oftalmologia_Fondo', NULL, 'input', NULL, NULL, 11.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (7.0, 'checkbox_oftalmologia_Conclusion', 'Conclusion:', 'checkbox', 'Apto, No Apto, Apto con Prescripcion', NULL, 12.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (7.0, 'input_oftalmologia_Observaciones', 'Observaciones:', 'input', NULL, NULL, 13.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (3.0, 'title_fonoaudiologia', 'FONOAUDIOLOGIA', 'text', NULL, NULL, 1.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (3.0, 'checkbox_fonoaudiologia_Antecedentes', 'Antecedentes auditivos patologicos:', 'checkbox', NULL, NULL, 2.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (3.0, 'file_fonoaudiologia_PDFAudiometria', 'PDF Audiometria:', 'file', NULL, NULL, 3.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (3.0, 'checkbox_fonoaudiologia_Conclusion', 'Conclusion:', 'checkbox', 'Apto, No Apto, Apto con Prescripcion', NULL, 4.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (3.0, 'input_fonoaudiologia_Observaciones', 'Observaciones:', 'input', NULL, NULL, 5.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (8.0, 'title_psicologia_1', 'INFORME PSICOLOGICO', 'text', NULL, NULL, 1.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (8.0, 'input_psicologia_1', 'El paciente se presento de manera organizada, esta ubicado en el tiempo y espacio, tiene juicio de realidad. A nivel cognitivo; sus funciones de la atencion, concentracion, memoria y calculo:', 'input', NULL, NULL, 2.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (8.0, 'input_psicologia_2', 'En cuanto a lo vincular, tiene relaciones:', 'input', NULL, NULL, 3.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (8.0, 'input_psicologia_3', 'y se maneja con actitud: ', 'input', NULL, NULL, 4.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (8.0, 'input_psicologia_4', 'Frente a las presiones externas el paciente posee:', 'input', NULL, NULL, 5.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (8.0, 'input_psicologia_5', 'En relacion a su personalidad se evidenciaron rasgos de:', 'input', NULL, NULL, 6.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (8.0, 'checkbox_psicologia_1', 'En el dia de la fecha, el paciente estaria en pleno uso de sus facultades mentales y se encontraria psicologicamente:', 'checkbox', 'Apto, No Apto, Apto con Prescripcion', NULL, 7.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (8.0, 'file_psicologia_InformePsicotecnico', 'Informe Psicotecnico', 'file', NULL, NULL, 8.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (8.0, 'input_psicologia_Observaciones', 'Observaciones:', 'input', NULL, NULL, 9.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (5.0, 'title_neumonologia_ESPIROMETRIA', 'ESPIROMETRIA', 'text', NULL, NULL, 1.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (5.0, 'title_neumonologia_ExamenRespiratorio', 'Examen Respiratorio', 'text', NULL, NULL, 2.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (5.0, 'checkbox_neumonologia_Vibraciones', 'Vibraciones vocales normal:', 'checkbox', NULL, NULL, 3.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (5.0, 'checkbox_neumonologia_Sibilancias', 'Sibilancias:', 'checkbox', NULL, NULL, 4.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (5.0, 'checkbox_neumonologia_Ruidos', 'Ruidos patologicos:', 'checkbox', NULL, NULL, 5.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (5.0, 'title_neumonologia_ESPIROMETRIA', 'ESPIROMETRIA', 'text', NULL, NULL, 6.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (5.0, 'checkbox_neumonologia_Fumador', 'Fumador:', 'checkbox', NULL, NULL, 7.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (5.0, 'input_neumonologia_Unidades', 'Unidades por dia', 'input', NULL, NULL, 8.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (5.0, 'input_neumonologia_StOx', 'St. Oxigeno:', 'input', NULL, NULL, 9.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (5.0, 'checkbox_neumonologia_Alergico', 'Alergico:', 'checkbox', NULL, NULL, 10.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (5.0, 'checkbox_neumonologia_Disnea', 'Disnea:', 'checkbox', NULL, NULL, 11.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (5.0, 'file_neumonologia_PDFEspirometria', 'PDF Espirometria', 'file', NULL, NULL, 12.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (5.0, 'checkbox_neumonologia_Conclusion', 'Conclusion:', 'checkbox', 'Apto, No Apto, Apto con Prescripcion', NULL, 13.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (5.0, 'input_neumonologia_Observaciones', 'Observaciones:', 'input', NULL, NULL, 14.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (9.0, 'title_rx_1', 'INFORME RADIOLOGICO', 'text', NULL, NULL, 1.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (9.0, 'title_rx_ColumnaLumbosacra', 'Informe de RX de Columna Lumbosacra', 'text', NULL, NULL, 2.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (9.0, 'file_rx_Frente1', 'Frente', 'file', NULL, NULL, 3.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (9.0, 'file_rx_Perfil1', 'Perfil', 'file', NULL, NULL, 4.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (9.0, 'file_rx_Oblicuo1', 'Oblicuo', 'file', NULL, NULL, 5.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (9.0, 'input_rx_Observaciones1', 'Observaciones:', 'input', NULL, NULL, 6.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (9.0, 'input_rx_Conclusion1', 'Conclusion:', 'input', NULL, NULL, 7.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (9.0, 'title_rx_ColumnaCervical', 'Informe de RX de Columna Cervical', 'text', NULL, NULL, 8.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (9.0, 'file_rx_Frente2', 'Frente', 'file', NULL, NULL, 9.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (9.0, 'file_rx_Perfil2', 'Perfil', 'file', NULL, NULL, 10.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (9.0, 'file_rx_Oblicuo2', 'Oblicuo', 'file', NULL, NULL, 11.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (9.0, 'input_rx_Observaciones2', 'Observaciones:', 'input', NULL, NULL, 12.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (9.0, 'input_rx_Conclusion2', 'Conclusion:', 'input', NULL, NULL, 13.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (9.0, 'title_rx_Torax', 'Informe de RX de Torax', 'text', NULL, NULL, 14.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (9.0, 'file_rx_Frente3', 'Frente', 'file', NULL, NULL, 15.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (9.0, 'file_rx_Perfil3', 'Perfil', 'file', NULL, NULL, 16.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (9.0, 'file_rx_Oblicuo3', 'Oblicuo', 'file', NULL, NULL, 17.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (9.0, 'input_rx_Observaciones3', 'Observaciones:', 'input', NULL, NULL, 18.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (9.0, 'input_rx_Conclusion3', 'Conclusion:', 'input', NULL, NULL, 19.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (9.0, 'title_rx_Rodilla', 'Informe de RX de Rodilla', 'text', NULL, NULL, 20.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (9.0, 'file_rx_Frente4', 'Frente', 'file', NULL, NULL, 21.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (9.0, 'file_rx_Perfil4', 'Perfil', 'file', NULL, NULL, 22.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (9.0, 'file_rx_Oblicuo4', 'Oblicuo', 'file', NULL, NULL, 23.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (9.0, 'file_rx_Observaciones4', 'Observaciones:', 'input', NULL, NULL, 24.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (9.0, 'input_rx_Conclusion4', 'Conclusion:', 'input', NULL, NULL, 25.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (9.0, 'title_rx_Pie', 'Informe de RX de Pie', 'text', NULL, NULL, 26.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (9.0, 'file_rx_Frente5', 'Frente', 'file', NULL, NULL, 27.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (9.0, 'file_rx_Perfil5', 'Perfil', 'file', NULL, NULL, 28.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (9.0, 'file_rx_Oblicuo5', 'Oblicuo', 'file', NULL, NULL, 29.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (9.0, 'input_rx_Observaciones5', 'Observaciones:', 'input', NULL, NULL, 30.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (9.0, 'input_rx_Conclusion5', 'Conclusion:', 'input', NULL, NULL, 31.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (9.0, 'checkbox_rx_ConclusionFinal', 'Conclusion Final:', 'checkbox', 'Apto, No Apto, Apto con Prescripcion', NULL, 32.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (9.0, 'input_rx_Observaciones', 'Observaciones:', 'input', NULL, NULL, 33.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (6.0, 'title_odontologia_1', 'EXAMEN ODONTOLOGICO', 'text', NULL, NULL, 1.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (6.0, 'title_odontologia_2', 'EXAMEN ODONTOLOGICO', 'text', NULL, NULL, 2.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (6.0, 'checkbox_odontologia_Caries', 'Caries:', 'checkbox', NULL, NULL, 3.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (6.0, 'checkbox_odontologia_Enfermedades', 'Enfermedades Odontologicas:', 'checkbox', NULL, NULL, 4.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (6.0, 'checkbox_odontologia_atencion', 'Necesita atencion odontologica:', 'checkbox', NULL, NULL, 5.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (6.0, 'file_odontologia_PDFOdontograma', 'PDF Odontograma', 'file', NULL, NULL, 6.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (6.0, 'checkbox_odontologia_Conclusion', 'Conclusion:', 'checkbox', 'Apto, No Apto, Apto con Prescripcion', NULL, 7.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (6.0, 'input_odontologia_Observaciones', 'Observaciones:', 'input', NULL, NULL, 8.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (1.0, 'title_cardiologia1', 'CARDIOLOGIA', 'text', NULL, NULL, 1.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (1.0, 'title_cardiologia2', 'EXAMEN CARDIOLOGICO', 'text', NULL, NULL, 2.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (1.0, 'input_cardiologia_TA1', 'TA 1o:', 'input', NULL, NULL, 3.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (1.0, 'input_cardiologia_TA2', 'TA 2o:', 'input', NULL, NULL, 4.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (1.0, 'input_cardiologia_FC', 'FC:', 'input', NULL, NULL, 5.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (1.0, 'checkbox_cardiologia_Taq', 'Taquicardias:', 'checkbox', NULL, NULL, 6.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (1.0, 'checkbox_cardiologia_Extrasistoles', 'Extrasistoles:', 'checkbox', NULL, NULL, 7.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (1.0, 'checkbox_cardiologia_Hipertension', 'Hipertension:', 'checkbox', NULL, NULL, 8.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (1.0, 'title_cardiologia_ELECTROCARDIOGRAMA', 'ELECTROCARDIOGRAMA', 'text', NULL, NULL, 9.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (1.0, 'combo_cardiologia_Ritmo', 'Ritmo:', 'combobox', 'Sinusal,No Sinusal, Irregular', NULL, 10.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (1.0, 'input_cardiologia_ComplejoORS', 'Complejo ORS:', 'input', NULL, NULL, 11.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (1.0, 'input_cardiologia_EjeQRS', 'Eje QRS:', 'input', NULL, NULL, 12.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (1.0, 'input_cardiologia_IntervaloPQ-PR', 'Intervalo PQ-PR:', 'input', NULL, NULL, 13.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (1.0, 'input_cardiologia_IntervaloQ-T', 'Intervalo Q-T:', 'input', NULL, NULL, 14.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (1.0, 'combo_cardiologia_TrazadoECG', 'Trazado ECG:', 'combobox', 'Normal,Apto,No Apto,Sugiero Electrocardiograma', NULL, 15.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (1.0, 'file_cardiologia_PDFElectrocardiograma', 'PDF Electrocardiograma', 'file', NULL, NULL, 16.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (1.0, 'checkbox_cardiologia_ConclusionElectrocardiograma', 'Conclusion Electrocardiograma:', 'checkbox', 'Apto, No Apto, Apto con Prescripcion', NULL, 17.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (1.0, 'input_cardiologia_Observaciones', 'Observaciones:', 'input', NULL, NULL, 18.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (1.0, 'title_cardiologia_ERGOMETRIA', 'ERGOMETRIA', 'text', NULL, NULL, 19.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (1.0, 'checkbox_cardiologia_Fumador', 'Fumador:', 'checkbox', NULL, NULL, 20.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (1.0, 'checkbox_cardiologia_Alergico', 'Alergico:', 'checkbox', NULL, NULL, 21.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (1.0, 'checkbox_cardiologia_Disnea', 'Disnea:', 'checkbox', NULL, NULL, 22.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (1.0, 'checkbox_cardiologia_CurvaCronotropica', 'Curva Cronotropica:', 'checkbox', NULL, NULL, 23.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (1.0, 'checkbox_cardiologia_CurvaTensional', 'Curva Tensional:', 'checkbox', NULL, NULL, 24.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (1.0, 'combo_cardiologia_Arritmias', 'Arritmias:', 'combobox', 'No, Esv Aisladas, Ev Aisladas, Ev Bigeminadas, TV No Sostenida', NULL, 25.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (1.0, 'combo_cardiologia_PEG', 'PEG:', 'combobox', 'Suficiente y Negativa para Isquemia Miocardiaca,Insuficiente y Negativa para Isquemia Miocardiaca hasta el doble producto, Positiva para Isquemia Miocardiaca', NULL, 26.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (1.0, 'file_cardiologia_PDFErgometria', 'PDF Ergometria', 'file', NULL, NULL, 27.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (1.0, 'checkbox_cardiologia_ConclusionErgometria', 'Conclusion Ergometria:', 'checkbox', 'Apto, No Apto, Apto con Prescripcion', NULL, 28.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (1.0, 'input_cardiologia_Observaciones2', 'Observaciones:', 'input', NULL, NULL, 29.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (4.0, 'title_laboratorio_ANALISISCLINICOS', 'ANALISIS CLINICOS', 'text', NULL, NULL, 1.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (4.0, 'file_laboratorio_PDF Estudio1', 'PDF Estudio 1', 'file', NULL, NULL, 2.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (4.0, 'file_laboratorio_PDF Estudio2', 'PDF Estudio 2', 'file', NULL, NULL, 3.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (4.0, 'checkbox_laboratorio_Conclusion', 'Conclusion:', 'checkbox', 'Apto, No Apto, Apto con Prescripcion', NULL, 4.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (4.0, 'input_laboratorio_Observaciones', 'Observaciones:', 'input', NULL, NULL, 5.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (NULL, 'title_neurologia1', 'NEUROLOGIA', 'text', NULL, NULL, 1.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (NULL, 'file_neurologia1', 'PDF 1', 'file', NULL, NULL, 2.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (NULL, 'file_neurologia2', 'PDF 2', 'file', NULL, NULL, 3.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (NULL, 'file_neurologia3', 'PDF 3', 'file', NULL, NULL, 4.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (NULL, 'file_neurologia4', 'PDF 4', 'file', NULL, NULL, 4.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (NULL, 'file_neurologia5', 'PDF 5', 'file', NULL, NULL, 4.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (NULL, 'file_neurologia6', 'PDF 6', 'file', NULL, NULL, 4.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (NULL, 'checkbox_neurologia_conclusion', 'Conclusion:', 'checkbox', 'Apto, No Apto, Apto con Prescripcion', NULL, 4.0,NULL);
INSERT INTO campos (id_area, name, label, type, options, default_value, form_orden, categoria_form) VALUES (NULL, 'input_neurologia_observaciones1', 'Observaciones:', 'input', NULL, NULL, 4.0,NULL);
