
CREATE TABLE `tipo_ficha` (
  `id` int NOT NULL AUTO_INCREMENT,
  `nombre_ficha` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
);


INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (1,'EXAMEN BASICO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (2,'EXAMEN ALTURA COMUN');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (3,'EXAMEN GUALCAMAYO+ SCREENING');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (4,'EX.  COMPLETO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (5,'EXAMEN CENTRAL DE RESTAURANT- ARAMARK');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (6,'EXAMEN DISEI - CONELCI (TCT)');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (7,'EXAMEN ELE SEGURIDAD');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (8,'EXAMEN CARNET PROFESIONAL');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (9,'EXAMEN REMA TIP TOP');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (10,'EXAMEN ENAEX');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (11,'EX. COMPLETO + EEG');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (12,'EX. LEY+CLS+AUDIO+PSICO+EEG');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (13,'EX. LEY +HUDLESSON+VDRL');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (14,'EX. LEY + SCREENING');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (15,'EX. LEY + RX. CLS');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (16,'SENDA');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (17,'LEY + PSICOTECNICO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (18,'EX. COMPLETO + LAB. COCINA');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (19,'CONSULTORA G Y M');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (20,'MINERA DON NICOLASEEG');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (21,'LEY + TEST');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (22,'LEY+ALCOHOLEMIA+SCREENING+PSICO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (23,'LEY+AUDIO+EEG+PSICO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (24,'LEY+VDRL+HUDLESSON+ESPIRO+AUDIO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (25,'LABORATORIO COMPLEMENTARIO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (26,'LEY+CLS+AUDIO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (27,'GUALCAMAYO S/ PSICO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (28,'LEY+AUDIO+SCREENING');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (29,'LEY CLS AUDIO PSICOTECNICO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (30,'LABORATORIO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (31,'LEY + AUDIO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (32,'LEY + PSICO + GYF');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (33,'LEY PSICOTECNCIO EEG');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (34,'COMPLETO + HIV + BENZO + ALCOHOLEMIA');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (35,'EX. LEY+GYF');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (36,'EX. LOMA NEGRA');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (37,'EX. CLINICO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (38,'EX. LEY +AUDIO+ESPIRO+PSICO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (39,'EX. GUALCAMAYO+SCREENING+ERGO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (40,'EX. LEY ESPIRO PSICO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (41,'AUDIO RX CLS');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (42,'EX.LEY+SCREENING+ESPIRO+AUDIO+RXCLS+EEG+TEST');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (43,'LEY+RX CLS+PSICO+AUDIO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (44,'PSICOTECNICO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (45,'LABORATORIO Y EX CLINICO PODER JUDICIAL');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (46,'ODONTOGRAMA - SCREENING');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (47,'EEG Y PSICOTECNICO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (48,'LEY+RXCL+ESPIRO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (49,'LEY +CLS+CERVI+AUDIO+ESPI+ERGO+PSICO+EEG');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (50,'EX OTALMO EEG PSICO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (51,'EX LEY RCLS AUDIO EEG PSICO OFT');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (52,'ERGOMETRIA');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (53,'ART DEPREMINSA');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (54,'EX.LEY+AUDIO+OFT+CLS+PSICO+EEG');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (55,'ALTURA PSICO SCRENING BENZO EEG');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (56,'MOSTOMAT');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (57,'LEY+RXCLS+PSICO+AUDIO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (58,'PSICOTECNICO DOCENTE');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (59,'TAMBOLAR');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (60,'DAMSU');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (61,'COOKINS');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (62,'ALTURA SCREENIN BENZO ALCOHOL EEG PSICO CERVICAL');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (63,'LEY CLS AUDIO ESPIRO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (64,'DAMSU CON PSICOTECNICO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (65,'LEY RX CLS RX CER AUDIO ESPIRO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (66,'TAMBOLAR 1');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (67,'LABORATORIO RX TORAX');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (68,'LABORATORIO PSICO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (69,'EEG ODONTOGRAMA');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (70,'CLINICO ECG');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (71,'EX COMPLETO + CERVICAL');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (72,'ESPIRO+PSICO+ERGO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (73,'EX LEY RX CLS RX CERV AUDIO PSICO EEG');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (74,'EXPERTA ART CLINICO ESPIRO TORAX');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (75,'ART CLINICO+OFT+HG');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (76,'LEY+CLS+PSICO+OFT+EEG+PERFIL LIPIDICO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (77,'EXA CLINICO+OFT+ HG');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (78,'OFT+RXCLS+PSICO+EEG');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (79,'EX. COMPLETO ALCOHOLEMIA');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (80,'EX LEY +CERVICAL+OFT');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (81,'LABORATORIO ESPIRO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (82,'LEY }+CLS+AUDIO+SCREENING+HC');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (83,'SAY INGIENIERIA +SCREENING+BENZO+ALCOHOL');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (84,'CLINICO +ERGO+ ELECTR');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (85,'CLINICO+ELECTRO+ESPIRO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (86,'ART SGS');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (87,'COOKINS EEG ERGO PSICO OFT SCREE BENZO ALCOHOLEMIA');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (88,'VISITA ANDES MINERA ELECRO + ESPIRO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (89,'LEY RX CLS EEG PSICO SCREENING AUDIO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (90,'LEY CLS AUDIO OFT EEG');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (91,'ART MOLINOS RIO DE LA PLATA');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (92,'RX CLS AUDIO EEG EX OTF');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (93,'JOSE MARIA - HEMOGLOBINA GLICOCILADA');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (94,'JOSE MARIA');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (95,'VISITA JOSE MARIA ERGO +55 AÑOS');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (96,'VISITA JOSE MARIA');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (97,'VISITA ANDES MINERA ELECTRO+ESPIRO+ERGO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (98,'EX. LEY CLS CERV PSICO EEG');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (99,'ALTURA TEST ALCOHOLEMIA EEG ERGOMETRIA PSICO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (100,'LEY RX CLS SCREENING');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (101,'REPRESAS PATAGONIA');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (102,'VALLECITO CON RX RODILLAS');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (103,'JOSE MARIA +COMPLEMENTARIO COCINA');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (104,'EX LEY SCREENING ALCOHOLEMIA');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (105,'LINDERO  SIN ERGO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (106,'LINDEROS  CON ERGO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (107,'CLINICO+LABORATORIO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (108,'LAB. HG. GLICOSILADA');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (109,'LEY+CLS+GYF+SCREENING+AUDIO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (110,'AUDIO PSICO EEG');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (111,'LEY+CLS+AUDIO+SCREENING+BENZO+ALCHOLEMIA');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (112,'EX SOUTH SCRENING BENZO ALCOHOLEMIA');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (113,'ALTURA BASICO+ ERGO+CERVICAL');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (114,'COMPLETO EEG ALCOHOLEMIA BENZO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (115,'LEY CLS AUDIO ESPIRO PSICO EEG BENZO SCREENING');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (116,'ALTURA BASICO+EEG+BENZO+SCREENING');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (117,'LEY+CLS+RX RODILLAS');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (118,'EX LEY +CLS+OFT');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (119,'EEG+LABORATORIO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (120,'EX ALTURA ERGO EEG PSICO COAGULOGRAMA');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (121,'LEY CLS ESPIRO ERGO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (122,'TORAX CLS EEG ERGO ECG OFTLABORATORIO OFT');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (123,'ALTURA COMUN+COALUGRAMA+EEG+ERGO+PSICO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (124,'CLINICO ECG TORAX CLS CERV PSICO LAB ESPIRO AUDIO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (125,'LEY +RX CLS+ RX RODILLAS');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (126,'LABORATORIO RX');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (127,'LEY SCREENING PSICO RX CERV');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (128,'EX CONCAT');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (129,'EX CLINICO+HEMOGRAMA+OFTALMO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (130,'EX CLINICO+ERGO+ECG+AUDIO+LAB+OFTA+RXTORAX+RXCLS');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (131,'LEY+CLS+CERVICAL+AUDIO+PSICO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (132,'LEY PSICO SCREENING PLIPIDICO HEP.');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (133,'LEY RX CLS VDRL  GYF AUDIO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (134,'EX KNIGHT  PIESOLD');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (135,'ALTURA RX CERVICAL PSICOTECNICO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (136,'EX FACULTAD LABORATORIO OFT AUDIO ECGPSICOTORAX');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (137,'LEY+ CLS+CERVICAL');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (138,'EX LEY RX CLS RX CERV. AUDIO LABORATORIO COMPL.');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (139,'ALTURA ERGO SCREENING BENZO HEP TG');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (140,'ROGGIO VIALMANI');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (141,' CUMMINS CLINICO+AUDIO+RXTORAX+LABOT.+OFT+ESPIRO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (142,'ART EMPAQUE CLINICO ESPIRO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (143,'COMPLETO + HIV MASTICADOR DE COCA? + ALCOHOLEMIA');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (144,'LEY+AUDIO+ESPIRO+RX CERVI+RXCLS');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (145,'GENDARMERIA');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (146,'FACU. LAB. OFT. SIN FO. AUDIO. ECG');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (147,'COMPLETO +EEG/ SIN ODONTO');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (148,'LEY CLS AUDIO EEG');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (149,'LABORATORIO+ECG+RX TORAX');
INSERT INTO `tipo_ficha` (`id`,`nombre_ficha`) VALUES (150,'LEY SCREENING EEG PSICO');
